<?php

return [
    'MERCADOPAGO_ACCESS_TOKEN' => env('MERCADOPAGO_ACCESS_TOKEN'),
    'MERCADOPAGO_USER_ID' => env('MERCADOPAGO_USER_ID'),
    'MERCADOPAGO_EXTERNAL_POS_ID' => env('MERCADOPAGO_EXTERNAL_POS_ID'),
];