apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: appautofastfood-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appautofastfood
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
